name: Docker Image CI

on:
  push:
    branches:
      - production

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          clean: 'false'

      - name: Login to HUB
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          run: |
          echo "DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD: ${{ env.DOCKER_PASSWORD }}"

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_NAME }}:production

  run_on_container:
    runs-on: ubuntu-latest
    needs: push_to_docker_hub
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.HOST_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script:
            docker stop ${{ env.CONTAINER_NAME }}
            docker rm ${{ env.CONTAINER_NAME }}
            docker run -d -p ${{ env.PORT }}:${{ env.PORT }} --restart unless-stopped --name ${{ env.CONTAINER_NAME }} -t -v /home/${{ env.HOST_USERNAME }}/log:/usr/src/app/log ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_NAME }}:production
