name: Docker Image CI

on:
  push:
    branches: [ "production" ]

jobs:
  push_to_docker_hub:
    runs-on: [self-hosted, production]
    strategy: 
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with: 
        clean: 'false'
    

    - name: Login to HUB
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_NAME }}:production
  
  run_on_container:
    runs-on: [self-hosted, production]
    needs: [push_to_docker_hub]
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script:
          docker stop ${{ secrets.CONTAINER_NAME }};
          docker rm ${{ secrets.CONTAINER_NAME }};
          docker run -d -p ${{ secrets.PORT }}:${{ secrets.PORT }} --restart unless-stopped --name ${{ secrets.CONTAINER_NAME }} -t -v /home/${{secrets.HOST_USERNAME}}/log:/usr/src/app/log ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_NAME }}:production
  
