name: Docker Image CI

on:
  push:
    branches:
      - production

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    environment: lambroghini
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          clean: 'false'

      - name: Login to HUB
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_NAME }}:latest

  deploy_image_on_vps:
    runs-on: ubuntu-latest
    environment: lambroghini
    needs: push_to_docker_hub
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script:
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_NAME }}:latest && docker stop ${{ secrets.DOCKER_NAME }} && docker rm ${{ secrets.DOCKER_NAME }} && docker run -p ${{ secrets.PORT }}:${{ secrets.PORT }} -d --restart on-failure --name ${{ secrets.DOCKER_NAME }} ${{secrets.DOCKER_USERNAME}}/${{ secrets.DOCKER_NAME }}:latest && docker image prune -f && docker logout